services:
  wiremock:
    image: wiremock/wiremock:3x
    command: --verbose
    ports:
      - "8787:8080"
    volumes:
      - ./.docker/wiremock:/home/wiremock/mappings

  algashop-postgres:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - algashop-postgres:/var/lib/postgresql
      - .docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  fastpay:
    image: algaworks/fastpay:latest
    restart: no
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      FASTPAY_HOSTNAME: http://localhost:9995
      DATABASE_JDBC_URL: jdbc:postgresql://algashop-postgres:5432/fastpay
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration,classpath:db/testdata
    ports:
      - "9995:9995"
    depends_on:
      algashop-postgres:
        condition: service_healthy

  algashop-mongodb-1:
    image: mongo:8
    command: [ "mongod", "--port", "27017", "--replSet", "rs0", "--bind_ip_all" ]
    restart: no
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27017:27017"
    volumes:
      - algashop-mongodb-1:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--port", "27017", "--eval", "db.adminCommand({ ping: 1 }).ok" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  algashop-mongodb-2:
    image: mongo:8
    command: [ "mongod", "--port", "27018", "--replSet", "rs0", "--bind_ip_all" ]
    restart: no
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27018:27018"
    volumes:
      - algashop-mongodb-2:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--port", "27018", "--eval", "db.adminCommand({ ping: 1 }).ok" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  algashop-mongodb-3:
    image: mongo:8
    command: [ "mongod", "--port", "27019", "--replSet", "rs0", "--bind_ip_all" ]
    restart: no
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27019:27019"
    volumes:
      - algashop-mongodb-3:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--port", "27019", "--eval", "db.adminCommand({ ping: 1 }).ok" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  algashop-mongodb-init:
    image: mongo:8
    restart: no
    depends_on:
      algashop-mongodb-1:
        condition: service_healthy
      algashop-mongodb-2:
        condition: service_healthy
      algashop-mongodb-3:
        condition: service_healthy
    entrypoint: [ "bash", "-c" ]
    volumes:
      - ./.docker/mongodb/init-replica-set.sh:/init-replica-set.sh
    command: [ "/init-replica-set.sh" ]

  algashop-redis:
    image: redis:8
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=algashop
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--requirepass', '${REDIS_PASSWORD}', '--appendonly', 'no', '--save', '', '--maxmemory', '480mb', '--maxmemory-policy', 'allkeys-lru' ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  algashop-postgres:
  algashop-mongodb-1:
  algashop-mongodb-2:
  algashop-mongodb-3: